# Generated by Django 4.1.7 on 2023-04-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('poc_first', models.CharField(blank=True, max_length=50)),
                ('poc_last', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('home', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('home', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('work', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('provider_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='HappyHome.provider')),
                ('user_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='HappyHome.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=1000)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyHome.review')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='HappyHome.category')),
                ('provider_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='HappyHome.provider')),
            ],
        ),
    ]
