# Generated by Django 4.1.7 on 2023-04-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
