# Generated by Django 4.1.7 on 2023-04-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHome', '0002_alter_category_options_alter_reply_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SiteUser',
        ),
    ]
